services:
  app:
    build: .
    working_dir: /app
    environment:
      LANG: C.UTF-8
    env_file:
      - .env
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./work:/app/work
      - ./scripts/docker:/app/scripts:ro
      - /etc/group:/etc/group:ro
    cap_drop:
      - ALL
